### ISSUE TITLE
Issue with certificates with 3k key lenght

### ISSUE THREAD

**Issue by MarcoL-4wardPRO** [microsoft/SPID-and-Digital-Identity-Enabler#15]
I've faced an issue trying to use certificates with a 3k key length.
Problem faced were:
- SPID Proxy Web App unable to open certificate private key with error "certificate password incorrect"
- Azure AD B2C user flow unable to open certificate private key for SAML message signing

Opening the certificate with MMC or openSSL worked without issues and the password was correctly accepted.

Recreating the certificate with same settings, but 2048 key length resolved all the issues.

**Comment by fume** [comment]
hi @MarcoL-4wardPRO, i just tried to generate a certificate with the spid-compliant-certificates tool (https://github.com/italia/spid-compliant-certificates) with a 3072 bit key and the SPIDProxy is opening and using it without issues. I didn't try (yet) to use the same certificate also as a SAML Message Signing key on AAD B2C but i will give it a try and share the outcome with you.

FYI, here you can find a screenshot of the certificate i'm currently using and it's working as expected
![image](https://user-images.githubusercontent.com/2969850/172734201-16410e1b-0fa2-412a-ba5b-4d78e44ef9ef.png)

**Comment by fume** [comment]
I'm not a certificate expert, but i'm pretty sure that key lengths should be multiple of 256 😄 
Let me know and we will eventually close this issue.

regards

**Comment by MarcoL-4wardPRO** [comment]
I'm pretty sure you are right, the strange part is that opening the certificate with OpenSSL or Windows MMC worked well.

I'll let you know my test results, regards.

**Comment by fume** [comment]
Were you opening the private key or the public one with OpenSSL and the Windows Certificate SnapIn?

Maybe just opening the certificate is fine, but when you need to use it the key length is important due to padding or similar. I repeat, i'm not a certificate expert but the non-256-multiple key length it's for sure a problem.

Let me know and if you resolve the problem, please close this issue as well.

thanks! Regards
