### ISSUE TITLE
Integrazione CNS Problemi

### ISSUE THREAD

**Issue by Reykrot** [microsoft/SPID-and-Digital-Identity-Enabler#64]
Buonasera, sono sempre io,
ho dei problemi con l'integrazione di CNS, in sostanza nel trustframeworkExtension devo inserire nei setting il valore:
   "CNSSAMLMetadata": "The metadata url for the CNS middleware. Used only if you want to use CNS"

questo valore è relativo alla webapp dove è situato il CNS

nella descrizione dell'installer la guida fa questo:

CNSSAMLMetadata si utilizza solo nel caso in cui si vuole abilitare il meccanismo di autenticazione tramite CNS. Nello specifico bisognerà inserire l'url statico dell'applicazione web contente i metadata necessari.

quindi ho preso ed ho messo la url di riferimento: https://nomebebapp.azurewebsites.net/cns/index

inserendo questa però vado in 403 - unahautorized
<img width="358" alt="image" src="https://github.com/microsoft/SPID-and-Digital-Identity-Enabler/assets/35104526/451e3b49-8708-4951-928d-6d7971f13992">

dietro a questo errore andando ad indagare c'è questo problema:

IN LOCALE HO QUESTO ERRORE:
<img width="377" alt="image" src="https://github.com/microsoft/SPID-and-Digital-Identity-Enabler/assets/35104526/543d3dbd-4b9d-4bba-adb4-3f0ef851447e">

eppure ho installato correttamente sia la card che la tessera sanitaria, mi viene letto il certificato all'interno del CNS, il punto è che il thumbprint che mi viene letto non è quello segnato in configurazione (f661b62b33233ab68b51aa1fa85ba18507ba634a) ma è questo: 57B2B9B20BB515639694819975D749B21754D9CD

SULLA WEBAPP PUBBLICATA:
ho l'errore medesimo ma perchè la lista: certStore.Certificates è vuota, sembra non leggermi nemmeno la scheda. 

dove sta l'errore nella configurazione? anche perchè se per testare tolgo l'autorizzazione va comunque in errore il Middleware.

se mi date supporto così come nell'altra issue, dove ho inserito la soluzione, posso mettere una miniguida leggermente più specifica per risolvere questo eventuale errore.

Grazie del supporto

**Comment by Reykrot** [comment]
EDIT: penso di aver compreso l'errore, la url corretta dovrebbe essere: https://nomebebapp.azurewebsites.net/cns/metadata

purtroppo però il certificato sulla scheda ancora non sono riuscito a farlo leggere credo tuttavia sia un problema di configurazione del pc locale

**Comment by fume** [comment]
ciao @Reykrot,
l'errore è legato alla configurazione della webapp: il CNSProxy, all'avvio, carica il certificato che verrà poi utilizzato per firmare le SAMLResponse. Il suddetto certificato è indicato al setting SAMLService:SigningCertificateThumbprint. Come puoi notare, nell'appsettings d'esempio viene proprio indicato "f661b62b33233ab68b51aa1fa85ba18507ba634a", ma è ovviamente un placeholder.

Puoi caricare il certificato nella sezione public certificates dell'app service e andando poi ad impostare il setting WEBSITE_LOAD_CERTIFICATES con valore * oppure con il thumbprint del certificato, che poi andrà riportate anche nel setting SAMLService:SigningCertificateThumbprint.

Ovviamente va configurato correttamente anche il setting SAMLService:SSOLocation con l'hostname corretto dell'appservice.

Inoltre, sempre sull'appservice, va abilitata la mutual authentication, facendo attenzione ad impostare il setting a "Require" ed aggiungendo il path /CNS/Metadata tra le esclusioni.
![image](https://github.com/microsoft/SPID-and-Digital-Identity-Enabler/assets/2969850/96f3545f-592d-45b8-985b-a0e12531b328)

**Comment by Reykrot** [comment]
Prossima settimana controllo e ti dico se risolvo, adesso come adesso sono fuori e non posso controllare

**Comment by Reykrot** [comment]
Piccolo Update: 
ho provveduto a modificare tutto il necessario che mi hai illustrato sopra, le configurazioni sono corrette, WEBSITE_LOAD_CERTIFICATES è settato su * e ho inserito il certificato all'interno della web app
<img width="867" alt="image" src="https://github.com/microsoft/SPID-and-Digital-Identity-Enabler/assets/35104526/8a5cd607-e892-43ad-b41a-2a371229a0f5">

ho correttamente inserito il thumbprint nelle configurazioni

in teoria dovrebbe essere tutto funzionante almeno per quanto riguarda la parte del certificato ma mi va in errore, non trova ancora il certificato.

questa parte di codice:
 using (X509Store certStore = new X509Store(StoreName.My, options.StoreLocation))
                {
                    certStore.Open(OpenFlags.ReadOnly);

                    X509Certificate2Collection certCollection = certStore.Certificates.Find(
                                                X509FindType.FindByThumbprint,
                                                options.SigningCertificateThumbprint,
                                                false);
                    // Get the first cert with the thumbprint (should be only one)
                    var signingCert = certCollection.OfType<X509Certificate2>().FirstOrDefault();

certCollection è vuoto.

 sto cercando di capire dove sta l'errore

**Comment by Reykrot** [comment]
Faccio un piccolo Edit, openssl3 ha modificato la tipologia di encription quindi il certificato inviato da Agid non può essere caricato direttamente sulla webapp, va modificato, il sistema migliore e funzionante che ho trovato per riuscire a inserire il certificato come .pfx (VEDI SCREEN)

<img width="851" alt="image" src="https://github.com/microsoft/SPID-and-Digital-Identity-Enabler/assets/35104526/07e9ae69-fb36-4d56-9c8c-ac1143765650">

è stato quello di caricarlo sul pc completo di chiave esportabile e esportarlo tramite il tool certlm presente in wondows,
<img width="510" alt="image" src="https://github.com/microsoft/SPID-and-Digital-Identity-Enabler/assets/35104526/a2451399-b5ee-4791-82da-da1f3b7d6f87">

una volta esportato correttamente con una password e l'emcription type come da screen

<img width="179" alt="image" src="https://github.com/microsoft/SPID-and-Digital-Identity-Enabler/assets/35104526/f3d62927-6f2b-46cf-97ad-4e83ac782b36">


sono riuscito a metterelo su Azure, tuttavia sebbene nei setting sia presente il valore di website_load_certificates come da screen

<img width="374" alt="image" src="https://github.com/microsoft/SPID-and-Digital-Identity-Enabler/assets/35104526/86041726-8ca0-49d1-9e51-12323c236776">


i certificati non vengono letti ne riconosciuti, ho modificato il log in caso di errore per vedere quanti certificati trova ma rimane 0.

non ho modificato ne la webapp ne altro. ci sono altre cose da fare per sbloccare i certificati e renderli visibili?

**Comment by Reykrot** [comment]
Ultimo Update, ho modificato il codice, non sono riuscito ad avere accesso ai Certificati nella macchina quindi ho implementato KeyVault e così pare funzionare tutto

**Comment by fume** [comment]
ciao, mi sono reso conto di aver fatto un typo importante sul mio messaggio precedente. Il certificato va caricato sui Private Certificates, non sui Public. E' strano che con il codice as-is tu non riesca a caricare il cert, ho installato questa versione proprio un paio di giorni fa e tutto è filato liscio.

**Comment by Reykrot** [comment]
Tanto, durante i miei vari test ho caricato il certificato in entrambi, comunque sia non è mai andato, dai log risulta sempre che ho 0 certificati registrati, sono riuscito a risolvere solamente utilizzando KeyVault, in locale funzionava, in remoto sul server non mi ha mai trovato nulla, ed il codice era intatto, il problema non è mai stato sul caricamento del certificato, perchè Alla fine il TripleDes sono riuscito a metterlo, ed anche l'altro, il punto è sempre stato che non mi trovava nessun certificato anche dopo averlo correttamente installato e correttamente reso raggiungibile con WEBSITE_LOAD_CERTIFICATES è settato su *.

ho risolto in altro modo penso che ora sia funzionante devo completare il giro trovando il pin della mia card ma penso che a quel punto sia apposto

**Comment by fume** [comment]
il pfx che stai usando è di test o è reale? Se puoi condividerlo faccio un double-check per capire cosa possa essere andato storto.

**Comment by Reykrot** [comment]
il .pfx che sto usando è quello di test che ci ha fornito agid, non so se posso condividerlo, non è stato richiesto da me e quindi devo sentire se può essere condiviso, ti faccio sapere in giornata

**Comment by Reykrot** [comment]
<img width="726" alt="image" src="https://github.com/microsoft/SPID-and-Digital-Identity-Enabler/assets/35104526/0445ab28-9059-4242-9e83-3a534ddfa7d9">

ho questo errore ma da cosa è dato cosa mi manca? la redirect è corretta riesco ad atterrare sulla index del cns

**Comment by Reykrot** [comment]
> Credo che il certificato caricato contenga solo la chiave pubblica e non quella privata (o quanto meno quella privata non è stata caricata correttamente)

già il problema è questo... sto cercando di capire come muovermi per poterlo risolvere, si accettano suggerimenti

**Comment by fume** [comment]
hai provato ad usare un certificato diverso da quello fornito da agid? Puoi provare a generare ed usare un self-signed?
`
New-SelfSignedCertificate -KeyExportPolicy Exportable -Subject "CN=yourappname.yourtenant.onmicrosoft.com" -KeyAlgorithm RSA -KeyLength 2048 -KeyUsage DigitalSignature -NotAfter (Get-Date).AddMonths(12) -CertStoreLocation "Cert:\CurrentUser\My"
`

**Comment by Reykrot** [comment]
appena provato con il certificato self made fatto con il comando powershell che mi hai indicato, non c'è differenza non viene rilevato nessun certificato, quando eseguo il comando semplicemente il count dei certificati presenti sulle macchina sono 0 che sia pubblico o privato

**Comment by fume** [comment]
ti sei accertato di aver configurato correttamente il thumbprint nell'appsettings?
Puoi condividere (anche in pvt se preferisci) l'appsettings.json attuale + le configurazioni applicate sull'App Service nel blade Configuration?

**Comment by Reykrot** [comment]
Come posso contattarti in privato? mi dai una mail ?

**Comment by fume** [comment]
Purtroppo il CertStore non può essere utilizzato su AppService for Linux. Per usare il codice as-is, dovrai utilizzare AppService su Windows.

In alternativa, se vuoi rimanere su AppService Linux, puoi modificare leggermente il codice per leggere il certificato dal filesystem come documentato qui: https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code. In particolare guarda la sezione https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code#load-certificate-in-linuxwindows-containers

L'uso del KeyVault è una buona alternativa. In questo caso fai attenzione perchè come "certificate" viene esposta solo la chiave pubblica. La chiave private è esposta come "secret".

**Comment by Reykrot** [comment]
messo KV nei secret... questa cosa è controintuitiva e non l'ho trovata scritta da nessuna parte ma c'è una documentazione di riferimento? perchè effettivamente il certificato preso da KV ha valorizzate entrambe le chiavi pubbliche e private, quindi sembra addirittura meglio rispetto alla sezione apposita... 

comunque ora sto modificando il codice per avviare tutto da KV o da Macchina (Linux) GRazie del supporto ho risolto tutto!

**Comment by fume** [comment]
Sulla docs di KV trovi le info in merito: https://learn.microsoft.com/en-us/azure/key-vault/certificates/about-certificates

in particolare nella sezione https://learn.microsoft.com/en-us/azure/key-vault/certificates/about-certificates#exportable-or-non-exportable-key si legge

**When a Key Vault certificate is created, it can be retrieved from the addressable secret with the private key in either PFX or PEM format**. The policy that's used to create the certificate must indicate that the key is exportable. **If the policy indicates that the key is non-exportable, then the private key isn't a part of the value when it's retrieved as a secret**.

Chiudo l'issue, mi fa piacere tu abbia risolto!
