### ISSUE TITLE
using the proxy with AAD 

### ISSUE THREAD

**Issue by Badjin-bit** [microsoft/SPID-and-Digital-Identity-Enabler#66]
Hi, thanks for your good work! 

I have an AAD (now entraID) tenant without  on-premises connection and I am trying to understand: is there any scenario in which one can have spid users log in to AAD as guests by using their SPID identity and leveraging this proxy?

Thanks!

**Comment by fume** [comment]
Hi @Badjin-bit , sorry for the late reply.

When using Entra ID, you can't let guest users authenticate via SPID.

You could let them authenticate via spid if they are "members" and you already have a federated domain with ADFS. In this case, on ADFS, you can customize the autnetication process and let them login with SPID, then "map" the SPID user to an AD user via their fiscalNumber.
